# Generated by Django 3.2.18 on 2023-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='item', to='customer.Category'),
        ),
    ]
